const year2020 = {
    year: 2021,
    months: [
    {
        name: "January",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
    {
        name: "February",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        ],
    },
    {
        name: "March",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
    {
        name: "April",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        ],
    },
    {
        name: "May",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
    {
        name: "June",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        ],
    },
    {
        name: "July",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
    {
        name: "August",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
    {
        name: "September",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        ],
    },
    {
        name: "October",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
    {
        name: "November",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        ],
    },
    {
        name: "December",
        days: [
        { day: 1, availablePeople: [] },
        { day: 2, availablePeople: [] },
        { day: 3, availablePeople: [] },
        { day: 4, availablePeople: [] },
        { day: 5, availablePeople: [] },
        { day: 6, availablePeople: [] },
        { day: 7, availablePeople: [] },
        { day: 8, availablePeople: [] },
        { day: 9, availablePeople: [] },
        { day: 10, availablePeople: [] },
        { day: 11, availablePeople: [] },
        { day: 12, availablePeople: [] },
        { day: 13, availablePeople: [] },
        { day: 14, availablePeople: [] },
        { day: 15, availablePeople: [] },
        { day: 16, availablePeople: [] },
        { day: 17, availablePeople: [] },
        { day: 18, availablePeople: [] },
        { day: 19, availablePeople: [] },
        { day: 20, availablePeople: [] },
        { day: 21, availablePeople: [] },
        { day: 22, availablePeople: [] },
        { day: 23, availablePeople: [] },
        { day: 24, availablePeople: [] },
        { day: 25, availablePeople: [] },
        { day: 26, availablePeople: [] },
        { day: 27, availablePeople: [] },
        { day: 28, availablePeople: [] },
        { day: 29, availablePeople: [] },
        { day: 30, availablePeople: [] },
        { day: 31, availablePeople: [] },
        ],
    },
],
};
  